# CMI

environment: integration
destination: "../cmi-www/_site/t/ftcm"

sourceId: 18
sid: FTCM
cmiTitle: "Teachings of Christ Mind"
siteName: "Library of Christ Mind Teachings"

# Setup
title:        'From the Christ Mind'
description:  'A channeled work'
url:          'https://www.christmind.info/t/ftcm'
baseurl:      ''
keywords:     "Jesus, Jeshua, Channeled Material"
home:         "/t/ftcm/"
port:         9918

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
semantic:     fui292
src-url:      'https://www.christmind.info/t/ftcm'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

# Collections for transcripts
collections:
  acq:
    output: true
    title: Get Acquainted
  book1:
    output: true
    title: "From the Christ Mind"
  book2:
    output: true
    title: "Fromm the Christ Mind: Book II"

defaults:

  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/ftcm/public/img/ftcm/acq-big.jpg"
      image-width: 612
      image-height: 918
      bid: "acq"
      audio: false
      pnumToggle: false

  - scope:
      path: ""
      type: book1
    values:
      layout: transcript
      book: "From the Christ Mind"
      publisher: "From the Christ Mind"
      image: "/t/ftcm/public/img/ftcm/book1-big.jpg"
      image-width: 612
      image-height: 918
      bid: "book1"
      audio: true

  - scope:
      path: ""
      type: book2
    values:
      layout: transcript
      book: "From the Christ Mind: Book II"
      publisher: "From the Christ Mind"
      image: "/t/ftcm/public/img/ftcm/book2-big.jpg"
      image-width: 612
      image-height: 918
      bid: "book2"
      audio: true

exclude: [
  bin, standalone, moved.html, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

